export const reactionEmojiMap = {
  LIKE: '❤️',
  DISLIKE: '👎',
  RECOMMEND: '👏',
  ANGRY: '😡',
  FLUSHED: '😳',
  STAR_STRUCK: '🤩',
  ROFL: '🤣',
  HOLDING_BACK_TEARS: '🥹',
  MIND_BLOWN: '🤯',
  POOP: '💩',
  CLOWN: '🤡',
  SKULL: '☠️',
  FIRE: '🔥',
  EYES: '👀',
  FROWN: '☹️',
  HOT: '🥵',
  EAGLE: '🦅',
  SPIDER: '🕷️',
  BAT: '🦇',
  CHINA: '🇨🇳',
  USA: '🇺🇸',
  JAPAN: '🇯🇵',
  KOREA: '🇰🇷',
}
